### ISSUE TITLE
dynamic schema attribute support

### ISSUE THREAD

**Issue by tomtau** [cipherstash/cipherstash-dynamodb#71]
We'd like to be able to add a dynamic "catch-all-other-attributes" field in a data struct, e.g.:

```
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    Searchable,
    Encryptable,
    Decryptable,
    Hash,
    PartialOrd,
)]
#[cipherstash(sort_key_prefix = None)]
pub struct Data {
      #[cipherstash(plaintext)]
      pub(crate) plain: String,
      pub(crate) protected: String,
      pub(crate) other_data: BTreeMap<String, String>,
}
```

where `other_data` contains all other attributes (the key is the attribute name, the value is the corresponding protected attribute value).
 `Encryptable` and `Decryptable` traits cannot be currently derived for `BTreeMap`. If we try to implement them manually we'll hit two issues:

1. `fn protected_attributes` is static
2. a way to list these other attributes in `fn from_unsealed` : I guess one could use `unsealed.protected()` and exclude the statically known attributes?

**Comment by auxesis** [comment]
Thanks for reporting this @tomtau. 

We think this is feasible, and will get back to you shortly with a rough timeline.

**Comment by coderdan** [comment]
Hi @tomtau I have a couple of clarifying questions if that's ok.

When sealing a `BTreeMap`, is it sufficient to encrypt the whole value and store the ciphertext as a hex string (or bytes) in Dynamo or do you want to be able to access each individual key within the map (and store using a Dynamo JSON type)?

Example of encrypting the whole map:

```rust
let mut other_data = BTreeMap::new();
movie_reviews.insert("a", "Data for A");
movie_reviews.insert("b", "Data for B");
// Encrypted (pseudo-code)
let enc: String = encrypt(other_data).encode_hex();
// => "61c2285f6c916307a4aa4fee1b5841b15620f..."
```

Or encrypting the values and storing the output as JSON:

```rust
let mut other_data = BTreeMap::new();
movie_reviews.insert("a", "Data for A");
movie_reviews.insert("b", "Data for B");
// Encrypted (pseudo-code)
let enc: BTreeMap<String, String> = encrypt(other_data);
// => {
//         "a" => "75201f3ff205545b4233ef68f5c",
//         "b" => "79271d66975a86739ef71374ac",
// }
```

Both are possible but the first is easier. It depends on your requirements.

Also, I assume that because you are using a BTreeMap and not a HashMap, value order is important. Am I correct in that assumption?

**Comment by coderdan** [comment]
No worries, thanks @tomtau!
